### ISSUE TITLE
Extension: Presentation Viewer

### ISSUE THREAD

**Issue by PrajwolAmatya** [JankariTech/web-app-presentation-viewer#1]
## Description
Create a web extension that will support the preview of a markdown file as a presentation slide using [reveal.js](https://revealjs.com/) presentation framework.

## User Story
- > As a user, I want to preview my markdown file so that the markdown file is loaded as a presentation slide.

## Pre-Condition
- Files should be a markdown file, for example, `presentation.md`.

## Acceptance Criteria
- Markdown file should be previewed as a presentation slide.

**Comment by grgprarup** [comment]
The first phase is completed with PR https://github.com/JankariTech/web-app-presentation-viewer/pull/6
