### ISSUE TITLE
[feature] Change slide theme according to oc web theme

### ISSUE THREAD

**Issue by grgprarup** [JankariTech/web-app-presentation-viewer#17]
# Description
Currently, the slide's theme defaults to the white theme of revealjs. The Owncloud web has two themes dark and light, adapt our slide to change the slide's theme according to the dark and light theme.

# Tasks to do
- [x] Adapt our slide's theme according to the dark and light theme of web

**Comment by koebel** [comment]
This should only affect slides that don't have a custom theme. For slide sets where background colours, font colours, etc. have been specified, no design changes should be made when the user changes between light and dark mode.
