### ISSUE TITLE
[feature] reveal.js syntax checker

### ISSUE THREAD

**Issue by koebel** [JankariTech/web-app-presentation-viewer#26]
only preview .md files with correct reveal.js syntax

from a usability and UX perspective it would be best for files where the syntax checker fails to
- either don't offer the preview in presentation viewer option (might be tricky when using the current web extension system)
- or show an error screen with a message that is easily understood by non technical users why their slides can't be previewed in this app

## User Story
As a user
I want to be informed if and why some .md files cant be properly displayed in the presentation viewer
So that I can solve the problem and once fixed preview my slides.

**Comment by individual-it** [comment]
The first solution would be problematic for performance reasons as it would require to read (at least part of the file) before displaying the list.
The second option sounds good to me, just need to think about how to detect issues correctly

**Comment by koebel** [comment]
I guess some high level feedback would be enough as a start :)

**Comment by koebel** [comment]
There are hardly no situations where the .md file can't be rendered
Only situations we can think about are empty .md file --> should display a single white slide
But even that case wouldn't break the app.

**Comment by koebel** [comment]
Closing this issue because it doesn't seem to be affecting the user experience much
