### ISSUE TITLE
[Bug] Fonts in /assets are not loaded correctly in the web viewer

### ISSUE THREAD

**Issue by saw-jan** [JankariTech/web-app-presentation-viewer#30]
After building the extension, we get `dist/assets` with some fonts in it. The extension tries to load the fonts in web without success. The font URLs are not the correct ones.

![Screenshot from 2024-02-28 17-39-39](https://github.com/JankariTech/web-app-presentation-viewer/assets/52366632/91f6b479-9189-4d28-ba26-00c0f22d93a9)

**Comment by saw-jan** [comment]
Maybe we can wait until https://github.com/owncloud/ocis/pull/8523

**Comment by koebel** [comment]
> Maybe we should wait for [owncloud/ocis#8523](https://github.com/owncloud/ocis/pull/8523), then don't have to do anything here

If you think this the issue mentioned above will fix this problem, I think it's completely fine to wait for this issue to be solved, in particularly also in light that this is not a paid project

**Comment by saw-jan** [comment]
I was hoping that it would solve but looks like we have to build with some config set to make it work properly

**Comment by fschade** [comment]
I can check the problem in the app pr, I still have to adjust some details.

**Comment by fschade** [comment]
> > I can check the problem in the app pr, I still have to adjust some details.
> 
> I believe the problem can be fixed while building the extension using vite config. I have tried in PR #32 and it works. But I don't know if this can be resolved from app PR.

i can confirm, the path must be relative to the file that imports the assets 🤗
