### ISSUE TITLE
[Bug]: single backtick is not recognizable as code block

### ISSUE THREAD

**Issue by individual-it** [JankariTech/web-app-presentation-viewer#39]
### Is there an existing issue for this?

- [X] I have searched for an existing issue

### Describe the bug

single backticks are not rendered as code

### Steps To Reproduce

1. create a presentation with this content
    ```
    At the command prompt, type `nano`.
    ```
2. check the rendered version

### Expected Behavior

according to https://www.markdownguide.org/basic-syntax/#code single backtick should be rendered as code

### Actual Behavior

I cannot see any difference in the font
![grafik](https://github.com/JankariTech/web-app-presentation-viewer/assets/2425577/e3163b1e-c8b5-4c89-84bd-5aa35e85af24)

### Environment

```markdown
- **OS**: Ubuntu 22.04
- **ownCloud Web**: ownCloud Web UI 8.0.0
- **oCIS**: Infinite Scale 5.0.0-RC4
```

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by koebel** [comment]
There is a difference in the font (it's best seen in letter "a") but I agree that the difference should be clearer. Maybe it's helpful to use a monospace font with `serifes` similar to the one that is used here in github?
