### ISSUE TITLE
[DOCS] Add documentations

### ISSUE THREAD

**Issue by grgprarup** [JankariTech/web-app-presentation-viewer#4]
- [x] Project Setup docs in README.md https://github.com/JankariTech/web-app-presentation-viewer/pull/8
- [ ] Add docs for markdown file format
- [ ] Add needed documentation

**Comment by koebel** [comment]
README.md needs some proof reading... Make sure to spell at least `ownCloud` properly :)

**Comment by koebel** [comment]
In my understanding the current version only allows preview of presentation files, not creation or modification. Is that correct? If so, the sentence `to create slide presentations directly from markdown files` in the description of the extension in `README.md` can lead to miss-understanding of the features provided. To make it clearer write something like `to preview slide presentations that were created in markdown files using the reveal.js syntax`

**Comment by koebel** [comment]
I've added a 1 sentence description in "About" plus some keywords. Please have a look.

**Comment by S-Panta** [comment]
Done https://github.com/JankariTech/web-app-presentation-viewer/pull/77
