### ISSUE TITLE
[Bug]: security vulnerability in fast-xml-parser & axios

### ISSUE THREAD

**Issue by koebel** [JankariTech/web-app-presentation-viewer#66]
### Is there an existing issue for this?

- [X] I have searched for an existing issue

### Describe the bug

I got some notifications from Github that there might be some security vulnerabilities in this repo. Please check.

![Screen Shot 2024-08-12 at 14 57 56](https://github.com/user-attachments/assets/8522f95b-8b43-48cc-8973-4e4cb8802aa2)

![Screen Shot 2024-08-13 at 14 20 17](https://github.com/user-attachments/assets/4f8bb2ac-2d01-4553-954a-c0f3f9493e77)

### Steps To Reproduce

-

**Comment by saw-jan** [comment]
Dependency updated in https://github.com/JankariTech/web-app-presentation-viewer/pull/70
