### ISSUE TITLE
[Feature]: getting presentation viewer into the app store 

### ISSUE THREAD

**Issue by koebel** [JankariTech/web-app-presentation-viewer#67]
### Description

check if all these points mentioned by Benedikt are covered before the next release: https://github.com/owncloud/web/issues/11330

- [x] manifest.json 
- [x] publicly available .zip file 
- [x] cover image
- [x] minimal QA on the app
- [x] add all information incl. screenshots to https://github.com/owncloud/awesome-ocis/blob/main/webApps/apps.json 

I think the first two points are already done for this app :)

### User Stories

As a creator of ocis web extensions
I want to my extension to be listed in the marketplace
So that users can find and install it easily

### Acceptance Criteria

all points above are implemented

**Comment by koebel** [comment]
now that release 2.0 is done, please make sure that the app gets added to the marketplace by adding it to https://github.com/owncloud/awesome-ocis/tree/main/webApps/owncloud/web-extensions

**Comment by saw-jan** [comment]
Closing as done
