### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by saw-jan** [JankariTech/web-app-presentation-viewer#71]
### PRE-RELEASE

-   [x] update [CHANGELOG.md](https://github.com/JankariTech/web-app-presentation-viewer/blob/main/CHANGELOG.md) entries
-   [x] bump version to `2.0.0`
    -   `package.json`
    -   `CHANGELOG.md`
-   [x] check successful CI runs

### QA
-   [x] [changelog](https://github.com/JankariTech/web-app-presentation-viewer/blob/main/CHANGELOG.md#unreleased) testing

### RELEASE

-   [x] create release tag `2.0.0`
    -   [x] successful CI run
-   [x] [release artifacts](https://github.com/JankariTech/web-app-presentation-viewer/releases/tag/2.0.0) are available
    - [x] check `mdpresentation-viewer-2.0.0.zip`

**Comment by S-Panta** [comment]
`2.0.0` release is done.

**Comment by saw-jan** [comment]
https://github.com/JankariTech/web-app-presentation-viewer/releases/tag/2.0.0
