### ISSUE TITLE
[Feature]: enable installation through yml file

### ISSUE THREAD

**Issue by koebel** [JankariTech/web-app-presentation-viewer#90]
### Description

For next oCIS release it is desired to enable installation of web extensions through yml file

### User Stories

Aa a system admin
I want to add Presentation Viewer as easily as possible to my environment
so that I have as little work as possible

### Acceptance Criteria

- create yml file to enable admins to add 3D Model Viewer with only a few lines in .env to the oCIS deployment example similar to https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_full/web_extensions
- add short description of what needs to be done by admin in README (copy yml file to "web_extensions" folder, add variable with path to the .env file, and append the variable to COMPOSE_FILE at the very end of the .env file)

**Comment by S-Panta** [comment]
I have release docker images https://hub.docker.com/r/jankaritech/md-presentation-viewer for release tag 2.0.0.
